version: "3"

services:
  datos:
    image: postgres:11
    environment:
      - POSTGRES_DB=datos
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=paco1999
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - datos
  
volumes:
  .:
  postgres_data:
  static:
      
