# Generated by Django 3.2.8 on 2021-10-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventario', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forma_pago', models.CharField(choices=[('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque')], default='efectivo', max_length=10)),
                ('cobro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recepcion', models.DateTimeField()),
                ('entrega', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
