# Generated by Django 3.2.8 on 2021-10-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='photo',
            field=models.ImageField(default='images/deafualt1.png', upload_to=''),
        ),
    ]
