# Generated by Django 3.2.8 on 2021-10-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='photo',
        ),
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.ImageField(default='images/deafualt1.png', upload_to=''),
        ),
    ]
