# Generated by Django 3.2.8 on 2021-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20211014_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('consolas', 'Consolas'), ('accesorios', 'Accesorios'), ('juegos', 'Juegos'), ('membresias', 'Membresías')], default='', max_length=10),
        ),
    ]
