# Generated by Django 3.2.8 on 2021-11-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='compañia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('consolas', 'Consolas'), ('accesorios', 'Accesorios'), ('juegos', 'Juegos'), ('membresias', 'Membresías')], default='Consolas', max_length=10),
        ),
    ]
