# Generated by Django 3.2.8 on 2021-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20211108_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
