# Generated by Django 3.2.8 on 2021-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_productoventa_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
