# Generated by Django 3.2.8 on 2021-11-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
