# Generated by Django 3.2.8 on 2021-11-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_carrito_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='photo',
            field=models.ImageField(default='images/deafualt1.png', upload_to=''),
        ),
    ]
