# Generated by Django 3.2.8 on 2021-11-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_carrito_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
