# Generated by Django 3.2.8 on 2021-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_carrito_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('Debito', 'Tarjeta de Débito'), ('Credito', 'Tarjeta de Crédito'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque')], default='efectivo', max_length=10),
        ),
    ]
