# Generated by Django 3.2.8 on 2021-11-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cobro',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ordenado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vuelto',
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='nit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
