# Generated by Django 3.2.8 on 2021-10-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(default='images/deafualt.png', upload_to='foto'),
        ),
    ]
